version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql.reto-ucu.net  
      DB_USER: ic_g7_admin
      DB_PASSWORD: Bd2025!
      DB_NAME: IC_Grupo7
      DB_PORT: 50006
      FLASK_APP: app.py
    depends_on: []

  frontend:
    build: ./frontend/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
