version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: host.docker.internal  # Esto conecta con tu base local
      DB_USER: root
      DB_PASSWORD: 1117
      DB_NAME: obligatorio
      FLASK_APP: app.py
    depends_on: []

  frontend:
    build: ./frontend/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
