version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: host.docker.internal  # Esto conecta con tu base local
      DB_USER: root
      DB_PASSWORD: tu_clave
      DB_NAME: votacion_db
    depends_on: []

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
